version: "3.3"

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock # Adicione esta linha
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DOCKER_IMAGE=${DOCKER_IMAGE}
      - DOCKER_CONTAINER_NAME=${DOCKER_CONTAINER_NAME}
    restart: unless-stopped
